# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'ui-base' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'Classy'
  pod 'pop'
  pod 'ChameleonFramework'
  pod 'IQKeyboardManager'
  pod 'Masonry'
  pod 'oc-string'


  # Pods for ui-base

  target 'ui-baseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ui-baseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
